# Generated by Django 4.1.7 on 2023-04-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_postcomment_postcommentreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcommentreply',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='postcommentreply',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='PostCommentReply',
        ),
    ]
